"""Module containing a set of prompt templates for COCO classes."""

classes = [
    'person',
    'bicycle',
    'car',
    'motorcycle',
    'airplane',
    'bus',
    'train',
    'truck',
    'boat',
    'traffic light',
    'fire hydrant',
    'stop sign',
    'parking meter',
    'bench',
    'bird',
    'cat',
    'dog',
    'horse',
    'sheep',
    'cow',
    'elephant',
    'bear',
    'zebra',
    'giraffe',
    'backpack',
    'umbrella',
    'handbag',
    'tie',
    'suitcase',
    'frisbee',
    'skis',
    'snowboard',
    'sports ball',
    'kite',
    'baseball bat',
    'baseball glove',
    'skateboard',
    'surfboard',
    'tennis racket',
    'bottle',
    'wine glass',
    'cup',
    'fork',
    'knife',
    'spoon',
    'bowl',
    'banana',
    'apple',
    'sandwich',
    'orange',
    'broccoli',
    'carrot',
    'hot dog',
    'pizza',
    'donut',
    'cake',
    'chair',
    'couch',
    'potted plant',
    'bed',
    'dining table',
    'toilet',
    'tv',
    'laptop',
    'mouse',
    'remote',
    'keyboard',
    'cell phone',
    'microwave',
    'oven',
    'toaster',
    'sink',
    'refrigerator',
    'book',
    'clock',
    'vase',
    'scissors',
    'teddy bear',
    'hair drier',
    'toothbrush'
]

coco_templates = [
    'a {}.',
    'a bad {}.',
    'a good {}.',
    'a small {}.',
    'a tiny {}.',
    'a big {}.',
    'a low contrast {}.',
    'a high contrast {}.',
    'a blurry {}.',
    'a zoomed in {}".',
    'a close up of a {}".',
    'an occluded {}.',
    'a partially visible {}.',
    'a partially hidden {}.',
    'a {} behind another object.',
]

coco_templates_with_descriptions = [
    'a {}, {}.',
    'a bad {}, {}.',
    'a good {}, {}.',
    'a small {}, {}.',
    'a tiny {}, {}.',
    'a big {}, {}.',
    'a low contrast {}, {}.',
    'a high contrast {}, {}.',
    'a blurry {}, {}.',
    'a zoomed in {}, {}.',
    'a close up of a {}, {}.',
    'an occluded {}, {}.',
    'a partially visible {}, {}.',
    'a partially hidden {}, {}.',
    'a {}, {}, behind another object.',
]

# coco_templates = [
#     'a {}.',
#     'a {} in the foreground.',
#     'a {} in the background.',
#     'a {} in the center.',
#     'a clearly visible {}.',
#     'a complete {}.',
#     'a {} viewed from the side.',
#     'a {} viewed from the front.',
#     'a distinctive {}.',
#     'a typical {}.',
#     'a well-defined {}.',
#     'a {} in its typical context.',
#     'a {} with clear boundaries.',
#     'a {} that stands out.',
#     'a recognizable {}.'
# ]

# coco_templates_with_descriptions = [
#     'a {}, {}.',
#     'a {} in the foreground, {}.',
#     'a {} in the background, {}.',
#     'a {} in the center, {}.',
#     'a clearly visible {}, {}.',
#     'a complete {}, {}.',
#     'a {} viewed from the side, {}.',
#     'a {} viewed from the front, {}.',
#     'a distinctive {}, {}.',
#     'a typical {}, {}.',
#     'a well-defined {}, {}.',
#     'a {} in its typical context, {}.',
#     'a {} with clear boundaries, {}.',
#     'a {} that stands out, {}.',
#     'a recognizable {}, {}.'
# ]

coco_class_to_synset_map = {
    'person': 'person.n.01',
    'bicycle': 'bicycle.n.01',
    'car': 'car.n.01',
    'motorcycle': 'motorcycle.n.01',
    'airplane': 'airplane.n.01',
    'bus': 'bus.n.01',
    'train': 'train.n.01',
    'truck': 'truck.n.01',
    'boat': 'boat.n.01',
    'traffic light': 'traffic_light.n.01',
    'fire hydrant': 'fireplug.n.01',  # Matched with fire_hydrant
    'stop sign': 'signboard.n.01',
    'parking meter': 'parking_meter.n.01',
    'bench': 'bench.n.01',
    'bird': 'bird.n.01',
    'cat': 'cat.n.01',
    'dog': 'dog.n.01',
    'horse': 'horse.n.01',
    'sheep': 'sheep.n.01',
    'cow': 'cow.n.01',
    'elephant': 'elephant.n.01',
    'bear': 'bear.n.01',
    'zebra': 'zebra.n.01',
    'giraffe': 'giraffe.n.01',
    'backpack': 'backpack.n.01',
    'umbrella': 'umbrella.n.01',
    'handbag': 'bag.n.04',
    'tie': 'necktie.n.01',
    'suitcase': 'bag.n.06',
    'frisbee': 'frisbee.n.01',
    'skis': 'ski.n.01',
    'snowboard': 'snowboard.n.01',
    'sports ball': 'ball.n.01',
    'kite': 'kite.n.03',
    'baseball bat': 'baseball_bat.n.01',
    'baseball glove': 'baseball_glove.n.01',
    'skateboard': 'skateboard.n.01',
    'surfboard': 'surfboard.n.01',
    'tennis racket': 'tennis_racket.n.01',
    'bottle': 'bottle.n.01',
    # Matched as wineglass and not wine_glass nor wine glass
    'wine glass': 'wineglass.n.01',
    'cup': 'cup.n.01',
    'fork': 'fork.n.01',
    'knife': 'knife.n.01',
    'spoon': 'spoon.n.01',
    'bowl': 'bowl.n.01',
    'banana': 'banana.n.02',
    'apple': 'apple.n.01',
    'sandwich': 'sandwich.n.01',
    'orange': 'orange.n.01',
    'broccoli': 'broccoli.n.01',
    'carrot': 'carrot.n.01',
    'hot dog': 'hotdog.n.02',
    'pizza': 'pizza.n.01',
    'donut': 'doughnut.n.02',
    'cake': 'cake.n.03',
    'chair': 'chair.n.01',
    'couch': 'sofa.n.01',
    # Might be both "Synset('pot.n.04') - a container in which plants are cultivated" or "Synset('plant.n.02') - (botany) a living organism lacking the power of locomotion"
    'potted plant': 'plant.n.02',
    'bed': 'bed.n.01',
    'dining table': 'dining_table.n.01',
    'toilet': 'toilet.n.02',
    'tv': 'television_receiver.n.01',
    'laptop': 'laptop.n.01',
    'mouse': 'mouse.n.04',
    'remote': 'remote_control.n.01',
    'keyboard': 'keyboard.n.01',
    # Matched as cellphone and not cell_phone
    'cell phone': 'cellular_telephone.n.01',
    'microwave': 'microwave.n.02',
    'oven': 'oven.n.01',
    'toaster': 'toaster.n.02',
    'sink': 'sink.n.01',
    'refrigerator': 'refrigerator.n.01',
    'book': 'book.n.02',
    'clock': 'clock.n.01',
    'vase': 'vase.n.01',
    'scissors': 'scissors.n.01',
    'teddy bear': 'teddy.n.01',
    'hair drier': 'hand_blower.n.01',  # Matched with hair_drier
    'toothbrush': 'toothbrush.n.01',
}


def compile_coco_prompts(class_name: str, description: str = None) -> list[str]:
    """Returns a list of COCO prompts for a given class name.

    :param class_name: class name of the object
    :type class_name: str
    :param description: description of the object, defaults to None
    :type description: str, optional
    :return: list of COCO prompts compiled with the class name and description
    :rtype: list[str]
    """
    if description is not None:
        return [template.format(class_name, description) for template in coco_templates_with_descriptions]
    return [template.format(class_name) for template in coco_templates]
